dist: xenial

language: node_js

node_js:
  - 10
  - 11
  - 12

env:
  - dir=app
  - dir=api

cache:
  directories:
    - $HOME/api/node_modules
    - $HOME/app/node_modules
  yarn: true
  
script:
  - cd $dir
  - yarn install --frozen-lockfile
  - yarn lint
  - yarn test  # --coverage
  - if [ $dir == "app" ];
    then yarn build --prod --base-href /beez/; 
    else yarn build;
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: app/dist/beez
  on:
    branch: master
    node_js: 12
    condition: "$dir = app"

jobs:
  exclude:
    - node_js: 11
      env: dir=app
      