language: node_js

node_js:
  - "14"

cache:
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test --coverage
  - yarn build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/beez
  on:
    branch: main
