dist: xenial

language: node_js

node_js:
  - "10"
  - "12"


cache:
  directories:
    - $HOME/api/node_modules
    - $HOME/app/node_modules
  cache: yarn

  
script:
  - cd app
  - yarn install --frozen-lockfile
  - yarn lint
  - yarn test  # --coverage
  - yarn build --prod --base-href /beez/ # base-href needed for github pages
  - cd ../api
  - yarn install --frozen-lockfile
  - yarn lint
  #- yarn test  # --coverage
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: app/dist/beez
  on:
    branch: master
